Modify Install Instructions to inform user that libfontconfig1-dev is required.
On Debian testing/sid when trying to run ./INSTALL it failed with:
```
x11.c:3:10: fatal error: fontconfig/fontconfig.h: No such file or directory
3 | #include <fontconfig/fontconfig.h>
| ^~~~~~~~~~~~~~~~~~~~~~~~~
```

And by using Sudo apt install libfontconfig1-dev fix this issule.

Fixes #4